ERROR 2022-09-21 18:59:21,506 assertbase.py _teardown_collect 273 <bound method FirstTest.test_01_bing_device of <minitest.FirstTest testMethod=test_01_bing_device>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/framework/libs/unittest/case.py", line 32, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/framework/libs/unittest/case.py", line 118, in run
    self._callTestMethod(testMethod)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/Users/isentech/Desktop/python/miniu_test/minitest.py", line 19, in test_01_bing_device
    self.assertCountEqual(page,'pagesDevice/addDevice/addDevice')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/framework/assertbase.py", line 354, in _hook_assert
    return attr(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 1206, in assertCountEqual
    self.fail(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 675, in fail
    raise self.failureException(msg)
AssertionError: Element counts were not equal:
First has 3, Second has 2:  '/'
